### ISSUE TITLE
Error using SyncRNG in Python

### ISSUE THREAD

**Issue by rpouillot** [GjjvdBurg/SyncRNG#3]
Hi,
I need to cross validate code in R and Python and am really interested in SyncRNG. Unfortunately, I got an error while trying your example code.
```
from SyncRNG import SyncRNG
s = SyncRNG(seed=123456)
for i in range(10):
    print(s.randi())

```
leads to
```
959852049
2573855645
OverflowError: Python int too large to convert to C long


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-1-b99e4ebd7f47>", line 4, in <module>
    print(s.randi())

  File "C:\ProgramData\Anaconda3\lib\site-packages\SyncRNG\__init__.py", line 22, in randi
    tmp = syncrng.rand(self.state)

SystemError: <built-in function rand> returned a result with an error set
```
Note:

```
import sys; print(sys.version)
3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
```

**Comment by GjjvdBurg** [comment]
Hi @rpouillot,

Thanks for reporting this issue, I'm sorry to hear you're having trouble with the code. I've just updated the Python package to a new version, could you check if this solves the issue?

**Comment by rpouillot** [comment]
Works perfectly now. Thank you!

**Comment by GjjvdBurg** [comment]
Great to hear, thanks for letting me know!
